
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: exvsn-backend-jenkins
    ports:
      - "8001:8000"
    environment:
      - MONGO_URI=mongodb+srv://abdullahrizwan2802:abdullah$$28@cluster0.5l1oo.mongodb.net/exvision_db?retryWrites=true&w=majority
      - DB_NAME=exvision_db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: exvsn-frontend-jenkins
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
